name = 'DEV Server'
port = 7788
players = 5
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
debug = true
website = '-'
language = 'de'
description = 'DEV Test Server'
modules = ['js-module', 'js-bytecode-module']
resources = ['charge']